import React,{useEffect,useRef,useState} from 'react';
import {DateTime} from 'luxon';
import {operationsConfig,request} from './config.js';
import Turnstile from './Turnstile.jsx';
import {contactEmailHref} from '../contact-config.js';
const initialZone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Athens';
const label=(iso,zone,locale)=>DateTime.fromISO(iso,{zone}).setLocale(locale).toLocaleString(DateTime.DATETIME_FULL);
export default function Booking({lang}) {
 const gr=lang==='el';const [zone,setZone]=useState(initialZone),[month,setMonth]=useState(()=>DateTime.now().startOf('month'));
 const [availability,setAvailability]=useState(null),[loadError,setLoadError]=useState(''),[loading,setLoading]=useState(false);
 const [day,setDay]=useState(''),[slot,setSlot]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState(''),[captcha,setCaptcha]=useState(''),[reset,setReset]=useState(0),[result,setResult]=useState(null);
 const [management]=useState(()=>{const p=new URLSearchParams(location.hash.slice(1));const value=p.get('id')&&p.get('token')?{id:p.get('id'),token:p.get('token')}:null;if(value)history.replaceState(null,'',location.pathname);return value;});
 const [meeting,setMeeting]=useState(null),[confirmed,setConfirmed]=useState(false);
 const key=useRef(crypto.randomUUID()),busy=useRef(false);
 const configured=operationsConfig.apiUrl&&operationsConfig.turnstileKey;
 async function refresh(){if(!configured)return;setLoading(true);setLoadError('');try{setAvailability(await request(`/slots?from=${month.minus({days:1}).toISODate()}&to=${month.endOf('month').plus({days:1}).toISODate()}`));}catch{setLoadError(gr?'Δεν μπορέσαμε να φορτώσουμε διαθέσιμες ώρες. Δοκίμασε ξανά.':'Availability could not be loaded. Please retry.');}finally{setLoading(false);}}
 useEffect(()=>{let active=true;if(!configured)return;setLoading(true);setLoadError('');setDay('');setSlot('');request(`/slots?from=${month.minus({days:1}).toISODate()}&to=${month.endOf('month').plus({days:1}).toISODate()}`).then(x=>{if(active)setAvailability(x);}).catch(()=>{if(active)setLoadError(gr?'Δεν μπορέσαμε να φορτώσουμε διαθέσιμες ώρες.':'Availability could not be loaded.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[month.toISODate(),configured,gr]);
 const message=e=>e.message==='SLOT_UNAVAILABLE'?(gr?'Αυτή η ώρα μόλις δεσμεύτηκε. Επίλεξε άλλη ώρα.':'This time is no longer available. Please choose another slot.'):e.message==='INVALID_TOKEN'?(gr?'Ο σύνδεσμος δεν είναι έγκυρος ή έχει λήξει. Επικοινώνησε μέσω email.':'This link is invalid or expired. Please contact us by email.'):(gr?'Η ενέργεια δεν ολοκληρώθηκε. Τα στοιχεία σου διατηρούνται· δοκίμασε ξανά.':'We could not complete this action. Your details are preserved; please retry.');
 async function manage(action){if(busy.current||!captcha)return;busy.current=true;setStatus('loading');setError('');try{const r=await request('/manage',{...management,action,starts_at:slot||undefined,turnstileToken:captcha});if(action==='details')setMeeting(r);else{setResult(r);setMeeting(m=>({...m,status:action==='cancel'?'cancelled':'confirmed',starts_at:slot||m.starts_at}));setConfirmed(false);}setStatus('success');}catch(e){setError(message(e));setStatus('error');if(e.message==='SLOT_UNAVAILABLE'){setSlot('');await refresh();}}finally{busy.current=false;setReset(n=>n+1);}}
 async function submit(event){event.preventDefault();if(busy.current||!slot||!captcha)return;const form=event.currentTarget;for(const name of ['name','topic'])form.elements[name].setCustomValidity(form.elements[name].value.trim()?'':(gr?'Συμπλήρωσε αυτό το πεδίο.':'Please fill in this field.'));if(!form.reportValidity())return;busy.current=true;setError('');setStatus('loading');const f=new FormData(form);try{const r=await request('/bookings',{name:f.get('name').trim(),email:f.get('email').trim(),topic:f.get('topic').trim(),company:f.get('company'),language:lang,timezone:zone,starts_at:slot,key:key.current,turnstileToken:captcha});setResult(r);setStatus('success');}catch(e){setError(message(e));setStatus('error');if(e.message==='SLOT_UNAVAILABLE'){setSlot('');key.current=crypto.randomUUID();await refresh();}}finally{busy.current=false;setReset(n=>n+1);}}
 const slots=availability?.slots||[];
 const days=new Map();for(const s of slots){const d=DateTime.fromISO(s.starts_at,{zone}).toISODate();if(!days.has(d))days.set(d,[]);days.get(d).push(s);}
 const start=month.startOf('month');const cells=[...Array(start.weekday-1).fill(null),...Array.from({length:month.daysInMonth},(_,i)=>start.plus({days:i}).toISODate())];
 const available=configured&&availability?.enabled;
 return <>
  <p className="ops-eyebrow">07 — LET’S BUILD / {management?'MANAGE MEETING':'BOOK A CONVERSATION'}</p>
  <h1>{gr?'Ας βρούμε χρόνο':'Let’s make time.'}<em>{gr?'για την ιδέα σου.':'For your idea.'}</em></h1>
  <p className="ops-lead">{gr?'Μια ουσιαστική συζήτηση είναι η αρχή για κάτι καλύτερο.':'A meaningful conversation is the beginning of something better.'}</p>
  {!configured||availability?.enabled===false?<div className="ops-panel ops-unavailable"><span className="ops-kicker">{gr?'ΣΥΝΑΝΤΗΣΕΙΣ':'MEETINGS'}</span><h2>{gr?'Οι online κρατήσεις θα ανοίξουν σύντομα.':'Online booking will open soon.'}</h2><p>{gr?'Μπορείς ήδη να ζητήσεις μια συνάντηση μέσω email. Θα βρούμε μαζί μια ώρα που σε εξυπηρετεί.':'You can already request a meeting by email. We’ll find a time that works for you.'}</p><a className="ops-button" href={contactEmailHref({interest:'Meeting'})}>{gr?'Ζήτησε συνάντηση μέσω email':'Request a meeting by email'} ⟶</a></div>:null}
  {configured&&loading&&<p role="status">{gr?'Φόρτωση διαθέσιμων ωρών…':'Loading available times…'}</p>}
  {loadError&&<p className="ops-error" role="alert">{loadError} <button onClick={refresh}>{gr?'Δοκίμασε ξανά':'Retry'}</button></p>}
  {management&&configured&&<section className="ops-panel"><h2>{gr?'Διαχείριση συνάντησης':'Manage your meeting'}</h2><p>{gr?'Η επίσκεψη στον σύνδεσμο δεν αλλάζει την κράτηση. Ολοκλήρωσε την επαλήθευση και επιβεβαίωσε την ενέργεια.':'Opening this link does not change your booking. Verify and confirm the action you want.'}</p><Turnstile action="manage" lang={lang} onToken={setCaptcha} reset={reset}/>{!meeting?<button disabled={!captcha||busy.current} onClick={()=>manage('details')}>{gr?'Δες την κράτησή σου':'View your booking'} ⟶</button>:<><p>{label(meeting.starts_at,zone,lang)} — {meeting.status}</p>{meeting.status==='confirmed'&&<><label className="ops-checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{gr?'Επιβεβαιώνω ότι θέλω ακύρωση ή αλλαγή.':'I confirm that I want to cancel or reschedule.'}</label><div className="ops-actions"><button disabled={!confirmed||!captcha||busy.current} onClick={()=>manage('cancel')}>{gr?'Ακύρωσε τη συνάντηση':'Cancel meeting'}</button><button disabled={!confirmed||!slot||!captcha||busy.current} onClick={()=>manage('reschedule')}>{gr?'Μεταφορά στην επιλεγμένη ώρα':'Reschedule to selected time'}</button></div></>}</>}{result&&<p role="status">{gr?'Η αλλαγή καταχωρίστηκε.':'Your change has been saved.'}</p>}</section>}
  {!management&&result?<section className="ops-panel" role="status"><span className="ops-kicker">{gr?'ΕΠΙΒΕΒΑΙΩΣΗ':'CONFIRMATION'}</span><h2>{gr?'Η ώρα σου δεσμεύτηκε.':'Your time is reserved.'}</h2><p>{label(slot,zone,lang)}</p><p>{availability?.duration} {gr?'λεπτά':'minutes'} · {availability?.location}</p><p>{gr?'Αναφορά κράτησης':'Booking reference'}: <strong className="ops-reference">{result.id}</strong></p><p>{gr?'Η επιβεβαίωση και η πρόσκληση ημερολογίου έχουν προγραμματιστεί για αποστολή στο email σου.':'Your confirmation and calendar invitation are queued for email delivery.'}</p></section>:available&&<div className="ops-booking-grid">
   <section className="ops-panel"><div className="ops-month"><button aria-label={gr?'Προηγούμενος μήνας':'Previous month'} disabled={status==='loading'||month<=DateTime.now().startOf('month')} onClick={()=>setMonth(m=>m.minus({months:1}))}>←</button><h2>{month.setLocale(lang).toFormat('LLLL yyyy')}</h2><button aria-label={gr?'Επόμενος μήνας':'Next month'} disabled={status==='loading'||month>=DateTime.now().plus({months:3}).startOf('month')} onClick={()=>setMonth(m=>m.plus({months:1}))}>→</button></div><label>{gr?'Η ζώνη ώρας σου':'Your timezone'}<select disabled={status==='loading'} value={zone} onChange={e=>{setZone(e.target.value);setDay('');setSlot('');key.current=crypto.randomUUID();}}>{[...new Set([initialZone(),'Europe/Athens','UTC',...(Intl.supportedValuesOf?.('timeZone')||[])])].map(z=><option key={z}>{z}</option>)}</select></label><div className="ops-calendar" role="group" aria-label={gr?'Επιλογή ημερομηνίας':'Choose date'}>{(gr?['Δ','Τ','Τ','Π','Π','Σ','Κ']:['M','T','W','T','F','S','S']).map((d,i)=><span className="ops-weekday" key={'w'+i}>{d}</span>)}{cells.map((d,i)=>d?<button key={d} disabled={status==='loading'||!days.has(d)} aria-label={DateTime.fromISO(d).setLocale(lang).toLocaleString(DateTime.DATE_FULL)} aria-pressed={day===d} onClick={()=>{setDay(d);setSlot('');key.current=crypto.randomUUID();}}>{DateTime.fromISO(d).day}</button>:<span key={'e'+i}/>)}</div><h3>{gr?'Διαθέσιμες ώρες':'Available times'}</h3><div className="ops-slots">{(days.get(day)||[]).map(s=><button key={s.starts_at} disabled={status==='loading'} aria-pressed={slot===s.starts_at} onClick={()=>{setSlot(s.starts_at);key.current=crypto.randomUUID();setError('');}}>{DateTime.fromISO(s.starts_at,{zone}).toFormat('HH:mm')}</button>)}</div>{!day&&<p>{gr?'Επίλεξε διαθέσιμη ημερομηνία.':'Choose an available date.'}</p>}{slots.length===0&&<p>{gr?'Δεν υπάρχουν διαθέσιμες ώρες αυτόν τον μήνα.':'There are no available times this month.'}</p>}</section>
   {!management&&<form className="ops-panel" onSubmit={submit} onInput={e=>{e.target.setCustomValidity?.('');if(!busy.current)key.current=crypto.randomUUID();}}><span className="ops-kicker">{gr?'Η ΣΥΖΗΤΗΣΗ ΜΑΣ':'OUR CONVERSATION'}</span><h2>{gr?'Πες μου λίγα για σένα.':'Tell me a little about you.'}</h2><p>{slot?label(slot,zone,lang):(gr?'Επίλεξε ώρα για να συνεχίσεις.':'Choose a time to continue.')}</p><p>{availability.duration} {gr?'λεπτά':'minutes'} · {availability.location}</p><fieldset disabled={status==='loading'}><label>{gr?'Όνομα':'Name'} *<input name="name" autoComplete="name" required maxLength={120}/></label><label>Email *<input type="email" name="email" autoComplete="email" required maxLength={254}/></label><label>{gr?'Θέμα συνάντησης':'Meeting topic'} *<textarea name="topic" required maxLength={2000} rows={4}/></label><div className="ops-honeypot" aria-hidden="true"><label>Company<input name="company" tabIndex={-1} autoComplete="off"/></label></div><Turnstile action="booking" lang={lang} onToken={setCaptcha} reset={reset}/><button className="ops-button" disabled={!slot||!captcha||status==='loading'}>{status==='loading'?(gr?'Καταχώριση…':'Reserving…'):(gr?'Επιβεβαίωσε τη συνάντηση':'Confirm meeting')} ⟶</button></fieldset></form>}
  </div>}
  {error&&<p className="ops-error" role="alert">{error}</p>}
 </>;
}
